version: "3.9"

services:
  backend:
    image: 158259501560.dkr.ecr.us-east-2.amazonaws.com/manga-api:latest
    container_name: manga-api
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - manga-net
    command uv run uvicorn app.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:7
    container_name: manga-redis
    restart: unless-stopped
    networks:
      -manga-net

  frontend:
    image: 158259501560.dkr.ecr.us-east-2.amazonaws.com/manga-frontend:latest
    container_name: manga-frontend
    restart: unless-stopped
    networks:
      - manga-net

  nginx:
    image: 158259501560.dkr.ecr.us-east-2.amazonaws.com/manga-nginx:latest
    container_name: manga-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - manga-net

networks:
  manga-net:
    name: manga-net