name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: build + push image to ecr
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: manga-api
            context: backend
          - name: manga-frontend
            context: frontend
          - name: manga-nginx
            context: nginx


    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Login to Zon ecr
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build, tag, and push ${{ matrix.service.name }} image to Zon ecr
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        IMAGE_URI=158259501560.dkr.ecr.us-east-2.amazonaws.com/${{ matrix.service.name }}
        docker build -t $IMAGE_URI:$IMAGE_TAG ${{ matrix.service.context }}
        docker push $IMAGE_URI:$IMAGE_TAG


  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: deploy by ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            cd ~
            docker compose pull
            docker compose up -d
